#!bin/bash
for dir in */; do    
    for book in $dir*.txt; do
        echo "Tokenising: $book"
	tr -sc 'A-Za-z' '\n' < $book | tr A-Z a-z | sort | uniq -c | sort -nr > ${book%.*}_tokenised.txt 
    done
done  
